version: '3'

services:

  demo-db:
    image: mysql

    restart: always
    environment:
      - MYSQL_DATABASE=city_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST_AUTH_METHOD=trust
    ports:
      - "3307:3306"
    container_name: demo-db

  demo-be:
    image: be
    restart: always
    ports:
      - "8080:8080"
    environment:
      #- DB_IP=172.22.0.2
      - DB_IP=demo-db
      - RABBIT_IP=demo-rabbit
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DBNAME=city_db

